in_putchar(char c);
voiswap_int(int *a, int *b);
in_strlen(char *s);
voi_puts(char *str);
voiprint_rev(char *s);
voirev_string(char *s);
voiputs2(char *str);
voiputs_half(char *str);
voiprint_array(int *a, int n);
cha*_strcpy(char *dest, char *src);
in_atoi(char *s);
